services: 
  s-ied1:
    container_name: S-IED1
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.34"
  
  s-ied2:
    container_name: S-IED2
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.35"

  s-ied3:
    container_name: S-IED3
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.36"

  s-ied4:
    container_name: S-IED4
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.37"
  
  t-ied1:
    container_name: T-IED1
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.50"
    
  t-ied2:
    container_name: T-IED2
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.51"

  t-ied3:
    container_name: T-IED3
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.52"

  g-ied1:
    container_name: G-IED1
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.2"

  m-ied1:
    container_name: M-IED1
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.18"

  m-ied2:
    container_name: M-IED2
    build:
      context: ./IED
    networks:
      scass:
        ipv4_address: "10.0.0.19"

  general-plc:
    container_name: General-PLC
    build:
      context: ./GeneralPLC
    networks:
      scass:
        ipv4_address: "10.0.0.65"

networks:
  scass:
    name: scass
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.0.0.0/24"
