services: 
  g-ied1:
    container_name: G-IED1
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-generation:
        ipv4_address: "192.168.72.82"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.94 &&
      ./run_script.sh"

  s-ied1:
    container_name: S-IED1
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.34"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.46 &&
      ./run_script.sh"
  
  s-ied2:
    container_name: S-IED2
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.35"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.46 &&
      ./run_script.sh"

  s-ied3:
    container_name: S-IED3
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.36"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.46 &&
      ./run_script.sh"

  s-ied4:
    container_name: S-IED4
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.37"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.46 &&
      ./run_script.sh"
  
  t-ied1:
    container_name: T-IED1
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-trasmission:
        ipv4_address: "192.168.72.50"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.62 &&
      ./run_script.sh"
    
  t-ied2:
    container_name: T-IED2
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-trasmission:
        ipv4_address: "192.168.72.51"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.62 &&
      ./run_script.sh"

  t-ied3:
    container_name: T-IED3
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-trasmission:
        ipv4_address: "192.168.72.52"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.62 &&
      tail -f /dev/null"

  m-ied1:
    container_name: M-IED1
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-microgrid:
        ipv4_address: "192.168.72.18"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.30 &&
      ./run_script.sh"

  m-ied2:
    container_name: M-IED2
    build:
      context: ./IED
    cap_add:
      - NET_ADMIN
    networks:
      scass-microgrid:
        ipv4_address: "192.168.72.19"
    command: >-
      sh -c "ip route del default &&
      ip route add default via 192.168.72.30 &&
      ./run_script.sh"

  general-plc:
    container_name: General-PLC
    user: root
    build:
      context: ./GeneralPLC
    cap_add:
      - NET_ADMIN
    networks:
      scass-scada:
        ipv4_address: "192.168.72.66"

  general-man:
    container_name: General-Man
    build:
      context: ./GeneralMan
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    networks:
      scass-scada:
        ipv4_address: "192.168.72.67"
    command: "tail -f /dev/null"

  internal-gateway:
    container_name: I-Gateway
    build:
      context: ./InternalGateway
    cap_add:
      - NET_ADMIN
    networks:
      scass-microgrid:
        ipv4_address: "192.168.72.30"
      scass-smarthome:
        ipv4_address: "192.168.72.46"
      scass-trasmission:
        ipv4_address: "192.168.72.62"
      scass-scada:
        ipv4_address: "192.168.72.78"
      scass-generation:
        ipv4_address: "192.168.72.94"
    command: >-
      sh -c "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth2 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth3 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth4 -j MASQUERADE &&
      iptables -A FORWARD -i eth0 -j ACCEPT &&
      iptables -A FORWARD -i eth1 -j ACCEPT &&
      iptables -A FORWARD -i eth2 -j ACCEPT &&
      iptables -A FORWARD -i eth3 -j ACCEPT &&
      iptables -A FORWARD -i eth4 -j ACCEPT &&
      tail -f /dev/null"
 
networks:     
  scass-microgrid:
    name: scass-microgrid
    driver: macvlan
    driver_opts:
      parent: eth0.2
    ipam:
      config:
        - subnet: "192.168.72.16/28"
  
  scass-smarthome:
    name: scass-smarthome
    driver: macvlan
    driver_opts:
      parent: eth0.3
    ipam:
      config:
        - subnet: "192.168.72.32/28"

  scass-trasmission:
    name: scass-trasmission
    driver: macvlan
    driver_opts:
      parent: eth0.4
    ipam:
      config:
        - subnet: "192.168.72.48/28"
  
  scass-scada:
    name: scass-scada
    driver: macvlan
    driver_opts:
      parent: eth0.5
    ipam:
      config:
        - subnet: "192.168.72.64/28"
          
  scass-generation:
    name: scass-generation
    driver: macvlan
    driver_opts:
      parent: eth0.6
    ipam:
      config:
        - subnet: "192.168.72.80/28"
