services: 
  sh-plc:
    container_name: SmartHome-PLC
    build:
      context: ./IED
    ports:
      - 502:502
    networks:
      grid:
        ipv4_address: 10.0.0.21

  t-plc:
    container_name: Trasmission-PLC
    build:
      context: ./IED
    ports:
      - 503:502
    networks:
      grid:
        ipv4_address: 10.0.0.22
    
  m-plc:
    container_name: MicroGrid-PLC
    build:
      context: ./IED
    ports:
      - 504:502
    networks:
      grid:
        ipv4_address: 10.0.0.23
  
  g-plc:
    container_name: Generation-PLC
    build:
      context: ./IED
    ports:
      - 505:502
    networks:
      grid:
        ipv4_address: 10.0.0.24

  general-plc:
    container_name: General-PLC
    build:
      context: ./GeneralPLC
    ports:
      - 1880:1880
    networks:
      grid:
        ipv4_address: 10.0.0.10

  test-node:
    container_name: Test-Node
    build:
      context: ./TestNode
    command: "tail -f /dev/null"
    networks:
      grid:
        ipv4_address: 10.0.0.100

  s-ied1:
    container_name: S-IED1
    build:
      context: ./IED
    networks:
      grid:
        ipv4_address: 10.0.0.41
  
  s-ied2:
    container_name: S-IED2
    build:
      context: ./IED
    networks:
      grid:
        ipv4_address: 10.0.0.42

  s-ied3:
    container_name: S-IED3
    build:
      context: ./IED
    networks:
      grid:
        ipv4_address: 10.0.0.43

  s-ied4:
    container_name: S-IED4
    build:
      context: ./IED
    networks:
      grid:
        ipv4_address: 10.0.0.44
  
  t-ied1:
    container_name: T-IED1
    build:
      context: ./IED
    networks:
      grid:
        ipv4_address: 10.0.0.31
    
  t-ied2:
    container_name: T-IED2
    build:
      context: ./IED
    networks:
      grid:
        ipv4_address: 10.0.0.32

  t-ied3:
    container_name: T-IED3
    build:
      context: ./IED
    networks:
      grid:
        ipv4_address: 10.0.0.33

  g-ied1:
    container_name: G-IED1
    build:
      context: ./IED_AMI
    networks:
      grid:
        ipv4_address: 10.0.0.51

  m-ied1:
    container_name: M-IED1
    build:
      context: ./IED_AMI
    networks:
      grid:
        ipv4_address: 10.0.0.61

  m-ied2:
    container_name: M-IED2
    build:
      context: ./IED_AMI
    networks:
      grid:
        ipv4_address: 10.0.0.62

    
networks:
  grid:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24