services: 
  s-ied1:
    container_name: S-IED1
    build:
      context: ./IED
    ports:
      - "10.0.0.41:502:502"
  
  s-ied2:
    container_name: S-IED2
    build:
      context: ./IED
    ports:
      - "10.0.0.42:502:502"

  s-ied3:
    container_name: S-IED3
    build:
      context: ./IED
    ports:
      - "10.0.0.43:502:502"

  s-ied4:
    container_name: S-IED4
    build:
      context: ./IED
    ports:
      - "10.0.0.44:502:502"
  
  t-ied1:
    container_name: T-IED1
    build:
      context: ./IED
    ports:
      - "10.0.0.31:502:502"
    
  t-ied2:
    container_name: T-IED2
    build:
      context: ./IED
    ports:
      - "10.0.0.32:502:502"

  t-ied3:
    container_name: T-IED3
    build:
      context: ./IED
    ports:
      - "10.0.0.33:502:502"

  g-ied1:
    container_name: G-IED1
    build:
      context: ./IED
    ports:
      - "10.0.0.51:502:502"

  m-ied1:
    container_name: M-IED1
    build:
      context: ./IED
    ports:
      - "10.0.0.61:502:502"

  m-ied2:
    container_name: M-IED2
    build:
      context: ./IED
    ports:
      - "10.0.0.62:502:502"