services: 
  s-ied1:
    container_name: S-IED1
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "10.0.0.34"
  
  s-ied2:
    container_name: S-IED2
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "10.0.0.35"

  s-ied3:
    container_name: S-IED3
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "10.0.0.36"

  s-ied4:
    container_name: S-IED4
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "10.0.0.37"
  
  t-ied1:
    container_name: T-IED1
    build:
      context: ./IED
    networks:
      scass-trasmission:
        ipv4_address: "10.0.0.50"
    
  t-ied2:
    container_name: T-IED2
    build:
      context: ./IED
    networks:
      scass-trasmission:
        ipv4_address: "10.0.0.51"

  t-ied3:
    container_name: T-IED3
    build:
      context: ./IED
    networks:
      scass-trasmission:
        ipv4_address: "10.0.0.52"

  g-ied1:
    container_name: G-IED1
    build:
      context: ./IED
    networks:
      scass-generation:
        ipv4_address: "10.0.0.2"

  m-ied1:
    container_name: M-IED1
    build:
      context: ./IED
    networks:
      scass-microgrid:
        ipv4_address: "10.0.0.18"

  m-ied2:
    container_name: M-IED2
    build:
      context: ./IED
    networks:
      scass-microgrid:
        ipv4_address: "10.0.0.19"

  general-plc:
    container_name: General-PLC
    build:
      context: ./GeneralPLC
    networks:
      scass-scada:
        ipv4_address: "10.0.0.65"

networks:
  scass-generation:
    name: scass-generation
    driver: macvlan
    driver_opts:
      parent: eth0.1
    ipam:
      config:
        - subnet: "10.0.0.0/28"
        - gateway: "10.0.0.1"
  
  scass-microgrid:
    name: scass-generation
    driver: macvlan
    driver_opts:
      parent: eth0.2
    ipam:
      config:
        - subnet: "10.0.0.16/28"
        - gateway: "10.0.0.17"
  
  scass-smarthome:
    name: scass-smarthome
    driver: macvlan
    driver_opts:
      parent: eth0.3
    ipam:
      config:
        - subnet: "10.0.0.32/28"
        - gateway: "10.0.0.33"

  scass-trasmission:
    name: scass-trasmission
    driver: macvlan
    driver_opts:
      parent: eth0.4
    ipam:
      config:
        - subnet: "10.0.0.48/28"
        - gateway: "10.0.0.49"
  
  scass-scada:
    name: scass-scada
    driver: macvlan
    driver_opts:
      parent: eth0.5
    ipam:
      config:
        - subnet: "10.0.0.64/29"
        - gateway: "10.0.0.65"