services: 
  g-ied1:
    container_name: G-IED1
    build:
      context: ./IED
    networks:
      scass-generation:
        ipv4_address: "192.168.72.82"

  s-ied1:
    container_name: S-IED1
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.34"
  
  s-ied2:
    container_name: S-IED2
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.35"

  s-ied3:
    container_name: S-IED3
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.36"

  s-ied4:
    container_name: S-IED4
    build:
      context: ./IED
    networks:
      scass-smarthome:
        ipv4_address: "192.168.72.37"
  
  t-ied1:
    container_name: T-IED1
    build:
      context: ./IED
    networks:
      scass-trasmission:
        ipv4_address: "192.168.72.50"
    
  t-ied2:
    container_name: T-IED2
    build:
      context: ./IED
    networks:
      scass-trasmission:
        ipv4_address: "192.168.72.51"

  t-ied3:
    container_name: T-IED3
    build:
      context: ./IED
    networks:
      scass-trasmission:
        ipv4_address: "192.168.72.52"



  m-ied1:
    container_name: M-IED1
    build:
      context: ./IED
    networks:
      scass-microgrid:
        ipv4_address: "192.168.72.18"

  m-ied2:
    container_name: M-IED2
    build:
      context: ./IED
    networks:
      scass-microgrid:
        ipv4_address: "192.168.72.19"

  general-plc:
    container_name: General-PLC
    build:
      context: ./GeneralPLC
    networks:
      scass-scada:
        ipv4_address: "192.168.72.66"

  internal-gateway:
    container_name: I-Gateway
    image: "ubuntu:22.04"
    networks:
      scass-microgrid:
        ipv4_address: "192.168.72.30"
      scass-smarthome:
        ipv4_address: "192.168.72.46"
      scass-trasmission:
        ipv4_address: "192.168.72.62"
      scass-scada:
        ipv4_address: "192.168.72.78"
      scass-generation:
        ipv4_address: "192.168.72.94"
        
networks:
  scass-microgrid:
    name: scass-microgrid
    driver: macvlan
    driver_opts:
      parent: eth0.2
    ipam:
      config:
        - subnet: "192.168.72.16/28"
          gateway: "192.168.72.30"
  
  scass-smarthome:
    name: scass-smarthome
    driver: macvlan
    driver_opts:
      parent: eth0.3
    ipam:
      config:
        - subnet: "192.168.72.32/28"
          gateway: "192.168.72.46"

  scass-trasmission:
    name: scass-trasmission
    driver: macvlan
    driver_opts:
      parent: eth0.4
    ipam:
      config:
        - subnet: "192.168.72.48/28"
          gateway: "192.168.72.62"
  
  scass-scada:
    name: scass-scada
    driver: macvlan
    driver_opts:
      parent: eth0.5
    ipam:
      config:
        - subnet: "192.168.72.64/28"
          gateway: "192.168.72.78"
          
  scass-generation:
    name: scass-generation
    driver: macvlan
    driver_opts:
      parent: eth0.6
    ipam:
      config:
        - subnet: "192.168.72.80/28"
          gateway: "192.168.72.94"
